sudo: required

addons:
  chrome: stable

language: node_js

node_js:
  - "10.13.0"

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - ".npm"
    - "~/.meteor"
    - "~/test/.meteor"
    - "~/test/node_modules"

notifications:
  email: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - cd $HOME
  - meteor create --bare test || true
  - cd test
  - mkdir packages || true
  - meteor --version
  - meteor add jquery
  - meteor add universe:i18n --allow-incompatible-update
  - meteor npm i --save selenium-webdriver@3.6.0 chromedriver simpl-schema
  - cd $TRAVIS_BUILD_DIR
  - export TEST_BROWSER_DRIVER=chrome
  - export UNIVERSE_I18N_LOCALES="en-US"
  - meteor test-packages ./ --settings ./tests/settings.coverage.json --once --driver-package meteortesting:mocha --test-app-path="$HOME/test"
